[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "scikit-learn",
    "torch<2.3.0"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::sklearn.exceptions.ConvergenceWarning"
]