[build-system]
requires = [
    "setuptools",
    "wheel",
    "numpy",
    "scikit-learn",
    "torch<=2.5.1"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::sklearn.exceptions.ConvergenceWarning"
]