name: Verify that tests pass on all platforms

on: [push]

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          rm -rf 0/
          flake8 cyanure_pytorch --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 cyanure_pytorch --count --max-complexity=10 --max-line-length=130 --statistics

  build_wheels:
    needs: [lint_code]
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

          
      - name: Install dependencies
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade pip
          python -m pip install --upgrade virtualenv
          python -m pip install setuptools wheel

      - name: Build the package
        run: python -m pip wheel -w wheelhouse .

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

  test_imports:
    needs: [build_wheels]
    name: Smoke test on raw ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Try to import cyanure
      run: pip install "scipy<=1.8.1" && pip install "numpy<=1.23.5" && pip install "scikit-learn<=1.1.3" && python -m pip install --no-index --find-links dist cyanure &&  python -c "import cyanure_pytorch;"
