name: Sphinx build

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python environment
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Update pip and install openblas
      run: |
        python -m pip install --upgrade pip
    - name: Install the package your documenting together with its dependencies.
      run: |
        pip install .
    - name: Install the building dependencies.
    # With higher version of docutils bullet lists does not work
      run: |
        pip install sphinx ipywidgets beautifulsoup4 sphinx-rtd-theme numpydoc furo autodocsumm docutils==0.16.0 pandas plotly dash==2.5.0 flask==2.2.3
    - name: Build the sphinx documentation and posts warnings as github comments.
      run: cd docs/sphinx/source && sphinx-build -b html . _build 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/sphinx/source/_build/